### ISSUE TITLE
[MGPG-78] gpg version parsing failure on Windows

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-gpg-plugin#157]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** opened **[MGPG-78](https://issues.apache.org/jira/browse/MGPG-78?redirect=false)** and commented

found during 3.0.0 release vote: https://lists.apache.org/thread.html/rcab83b862f15ca276aab3fc61cd4192e1a67a35a2a6ce7ad4c7994b1%40%3Cdev.maven.apache.org%3E

```
Caused by: java.lang.IllegalArgumentException: Can't parse version of
gpg (GnuPG) 2.0.26 (Gpg4win 2.2.3)
    at org.apache.maven.plugins.gpg.GpgVersion.compareTo(GpgVersion.java:60)
    at org.apache.maven.plugins.gpg.GpgVersion.isBefore(GpgVersion.java:101)
    at org.apache.maven.plugins.gpg.GpgSigner.generateSignatureForFile(GpgSigner.java:89)
    at org.apache.maven.plugins.gpg.AbstractGpgSigner.generateSignatureForArtifact(AbstractGpgSigner.java:203)
    at org.apache.maven.plugins.gpg.GpgSignAttachedMojo.execute(GpgSignAttachedMojo.java:178)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
```

The version on the command line:

```
$ gpg --version
gpg (GnuPG) 2.0.26 (Gpg4win 2.2.3)
libgcrypt 1.6.2
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
 [show/hide original text] 
```

---

**Affects:** 3.0.0 (cancelled)

**Remote Links:**
- [GitHub Pull Request #8
](https://github.com/apache/maven-gpg-plugin/pull/8)

**Comment by jira-importer** [comment]
**[Tibor Digana](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibor17)** commented

https://gitbox.apache.org/repos/asf?p=maven-gpg-plugin.git;a=commit;h=cd0f6d394d5ca0cc6bca77928809953dbb0e736b
