### ISSUE TITLE
[MGPG-20] Signing fails if project has no main artifact but only attached artifacts with classifiers

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-gpg-plugin#187]
**[Clement Escoffier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clement.escoffier)** opened **[MGPG-20](https://issues.apache.org/jira/browse/MGPG-20?redirect=false)** and commented

I've a project creating two artifacts with different classifiers.
When I try to sign them, I get :
gpg: .../target/classes: read error: Is a directory

Here is the stack trace in verbose mode:
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Exit code: 2
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exit code: 2
at org.apache.maven.plugin.gpg.GpgSigner.generateSignatureForArtifact(GpgSigner.java:179)
at org.apache.maven.plugin.gpg.GpgSignAttachedMojo.execute(GpgSignAttachedMojo.java:228)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more

If I change the configuration to generate only one artifact, it works (and the artifacts are signed).

---

**Affects:** 1.0-alpha-4

**Attachments:**
- [GPG-Classifier-Test.zip](https://issues.apache.org/jira/secure/attachment/12716538/GPG-Classifier-Test.zip) (_11.59 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12716539/pom.xml) (_2.05 kB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

We use the plugin on a regular basis to sign the source and javadoc artifacts without issues and the few information provided isn't sufficient for an analysis. So please reopen with a demo project that reproduces the issue.

**Comment by jira-importer** [comment]
**[Clement Escoffier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clement.escoffier)** commented

The issue is still valid. I'm going to upload a pom file to reproduce it.

**Comment by jira-importer** [comment]
**[Clement Escoffier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clement.escoffier)** commented

Upload a pom file reproducing the issue (as well as a project).
The issue comes when the project does not generate an artifact named regularly but always use classifier (in the project -jdk13 and -jdk15).

Launching mvn clean package gpg:sign failed
Removing the jdk15 classifier fixes the issue.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r949366](http://svn.apache.org/viewvc?view=revision&revision=949366),thanks for the example project.
